source 'https://rubygems.org'

# git_source(:github) do |repo_name|
#   repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
#   "https://github.com/#{repo_name}.git"
# end

ruby "2.6.3"

gem "json-streamer"
gem "easy_logging"
gem "rails"
gem "pg"
