name: GitHub Actions Workflow with Flutter installation cache

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      flutter_version: "1.2.1"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
