name: Flutter basics

on: [push]

env:
  flutter_version: "1.9.1+hotfix.6"
  java_version: "12.x"

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: |
          cd flutter-basics
          flutter pub get
      - name: Lint
        run: |
          cd flutter-basics
          flutter format --dry-run . --set-exit-if-changed

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: |
          cd flutter-basics
          flutter pub get
      - name: Lint
        run: |
          cd flutter-basics
          flutter analyze

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: |
          cd flutter-basics
          flutter pub get
      - name: Test
        run: |
          cd flutter-basics
          flutter test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [format, lint, test]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Install dependencies
        run: |
          cd flutter-basics
          flutter pub get
      - name: Build
        run: |
          cd flutter-basics
          flutter build apk
