# name: GitHub Action with NPM cache

# on: [push]

# jobs:
#   verify:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: ./github-action-npm-cache

name: GitHub Action with NPM cache

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-${{ hashFiles('./github-action-npm-cache/package-lock.json') }}
    - name: Install NPM dependencies
      run: yarn install
