name: Inline Rails

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: inline-rails/vendor/bundle
        key: ${{ runner.OS }}-inline-rails-${{ hashFiles('**/inline-rails/inline-rails.rb') }}
        restore-keys: |
          ${{ runner.OS }}-inline-rails-
    - name: Execute
      run: BUNDLE_PATH=inline-rails/vendor/bundle ruby inline-rails/inline-rails.rb
