name: Inline Rails

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Print debug info
      run: echo $BUNDLE_PATH
    - name: Print debug info
      run: echo $GEM_HOME
    - name: Print debug info
      run: echo $GEM_PATH
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: /usr/local/bundle
        key: ${{ runner.OS }}-inline-rails-${{ hashFiles('**/inline-rails/inline-rails.rb') }}
        restore-keys: |
          ${{ runner.OS }}-inline-rails-
    - name: Execute
      run: ruby inline-rails/inline-rails.rb
