name: Memoization in hooks and contexts

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: react-hook-context-memo/node_modules
        key: ${{ runner.OS }}-react-hook-context-memo-${{ hashFiles('**/react-hook-context-memo/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-react-hook-context-memo-
    - name: Install NPM dependencies
      run: cd react-hook-context-memo && yarn install
    - name: Lint
      run: cd react-hook-context-memo && yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: react-hook-context-memo/node_modules
        key: ${{ runner.OS }}-react-hook-context-memo-${{ hashFiles('**/react-hook-context-memo/yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-react-hook-context-memo-
    - name: Install NPM dependencies
      run: cd react-hook-context-memo && yarn install
    - name: Build
      run: cd react-hook-context-memo && yarn build
